services:
  - type: web
    name: gamalek-store
    env: node
    region: frankfurt
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    disk:
      name: persistent_disk
      mountPath: /opt/render/project/src/data
      sizeGB: 5
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

